homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.htmlcode, name='HTMLcode'),
    path('contact/', views.contact, name='contact'),
    # dilanjutkan ...
    path('hobby/', views.hobby, name='hobby'),
    path('pendidikan/', views.pendidikan, name='pendidikan'),
    path('matakuliah/', views.MatKul, name='matakuliah'),
    path("kegiatan/",views.kegiatan, name='kegiatan'),
    path("addpengikut/<id_add>",views.addpengikut, name='addpengikut'),
    path("searchbarbooks/",views.books,name='books'),
    path("delete/<id_delete>",views.delete, name='delete'),    
    path("signup/",views.signup, name ='signup'),
    path("signin/",views.signin, name ='signin'),
    path("logout/",views.logout1, name ='logout'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.
class MataKuliah(models.Model):
    id = models.AutoField(primary_key=True,)
    namaMatkul = models.CharField(max_length = 50)
    namaDosen = models.CharField(max_length = 50)
    jumlahSks = models.IntegerField()
    descMatkul = models.CharField(max_length = 50)
    semester = models.IntegerField()
    ruangKelas = models.CharField(max_length = 50)

class Kegiatan(models.Model):
    id = models.AutoField(primary_key=True,)
    namaKegiatan = models.CharField(max_length = 50)

class Pengikut(models.Model):
    namaPengikut = models.CharField(max_length = 50)
    kegiatan = models.ForeignKey(Kegiatan,on_delete=models.CASCADE)
    
    
    
    

homepage/forms.py
from django import forms
from .models import MataKuliah,Kegiatan,Pengikut

class MataKuliahForms(forms.ModelForm):
    class Meta : 
        model = MataKuliah
        fields = ["namaMatkul","namaDosen","jumlahSks","descMatkul","semester","ruangKelas"]
        widgets = {
            'namaMatkul':forms.TextInput(attrs={'class':'form-control'}), 
            'namaDosen':forms.TextInput(attrs={'class':'form-control'}),
            'jumlahSks':forms.NumberInput(attrs={'class':'form-control'}),
            'descMatkul':forms.TextInput(attrs={'class':'form-control'}),
            'semester':forms.NumberInput(attrs={'class':'form-control'}),
            'ruangKelas':forms.TextInput(attrs={'class':'form-control'})}
    
class KegiatanForms(forms.ModelForm):
    class Meta : 
        model = Kegiatan
        fields = ["namaKegiatan"]
        widgets = {
            'namaKegiatan':forms.TextInput(attrs={'class':'form-control'}),}
            
class PengikutForms(forms.ModelForm):
    class Meta : 
        model = Pengikut
        fields = ["namaPengikut"]
        widgets = {
            'namaPengikut':forms.TextInput(attrs={'class':'form-control'}),}


    
    

homepage/views.py
from django.shortcuts import render,redirect
from .models import MataKuliah,Kegiatan,Pengikut
from .forms import MataKuliahForms,KegiatanForms,PengikutForms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout


# Create your views here.
def contact(request):
    return render(request, 'story3CONTACT.html')
def hobby(request):
    return render(request, 'story3HOBBY.html')
def htmlcode(request):
    return render(request, 'story3HTMLcode.html')
def pendidikan(request):
    return render(request, 'story3PENDIDIKAN.html')
def MatKul(request):
    if request.method ==  "POST":
        form1 = MataKuliahForms(request.POST)
        if form1.is_valid():
            form1.save()
            return redirect('homepage:matakuliah')
    else :      
        form = MataKuliahForms()
        return render(request, 'story5MatKul.html',{"form_html" : form,"list_matkul" :  MataKuliah.objects.all()})
def kegiatan(request):
    if request.method == "POST":
        form1 = KegiatanForms(request.POST)
        if form1.is_valid():
            form1.save()
            return redirect('homepage:kegiatan')
    if len(Kegiatan.objects.all()) == 0 :
        forms1 = KegiatanForms()
        forms2 = ""
    else :
        forms1 = KegiatanForms()
        forms2 = PengikutForms()
    return render(request, 'Story6Kegiatan.html',{"form_html1" : forms1,"form_html2" : forms2,"list_kegiatan" :  Kegiatan.objects.all()})

def addpengikut(request,id_add):
    namaPengikutBaru = request.POST["namaPengikut"]
    kegiatanBaru = Kegiatan.objects.get(id = id_add)
    pengikut = Pengikut.objects.create(namaPengikut = namaPengikutBaru , kegiatan = kegiatanBaru)
    return redirect('homepage:kegiatan')

def books(request):
    return render(request,'SearchBarBooks.html')

def signup(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = User.objects.create_user(username = username , password = password)
        return redirect('homepage:HTMLcode')
    else :
        return render(request,'Signup.html')

def signin(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username = username , password = password)
        if user != None :
            login(request,user)
            
            return redirect('homepage:HTMLcode')
        else :
            return redirect('homepage:signin')
    else :
        return render(request,'Signin.html')
    
def logout1(request):
    logout(request)
    return redirect('homepage:HTMLcode')
 
def delete(request,id_delete):
    MataKuliah.objects.filter(id = id_delete).delete()
    return redirect('homepage:matakuliah')
           

homepage/templates/SearchBarBooks.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'story3CSScode.css' %}"> 
        <title>WEBSITE PROFILE ZAIDAN ARIIQ</title>
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    </head>

<body>
    <!-- BAGIAN NAVIGATOR BAR -->
    <nav class="navbar navbar-expand-sm" id="navigation_bar">
        <a class="navbar-brand" href="{% url 'homepage:HTMLcode' %}" id="logo_nama">
            ZSELAMAT DATANG {{ user }}
        </a>
        
        
    <!-- ISI DALAM NAVIGATION BAR -->
        <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link navbar-judul" href="{% url 'homepage:hobby' %}">HOBBY</a>
        </li>
        <li class="nav-item">
            <a class="nav-link navbar-judul" href="{% url 'homepage:pendidikan' %}">PENDIDIKAN</a>
        </li>
        <li class="nav-item">
            <a class="nav-link navbar-judul" href="{% url 'homepage:contact' %}">CONTACT</a>
        </li>
        <li class="nav-item">
          <a class="nav-link navbar-judul" href="{% url 'homepage:matakuliah' %}">MATAKULIAH</a>
        </li>
        <li class="nav-item">
          <a class="nav-link navbar-judul" href="{% url 'homepage:kegiatan' %}">KEGIATAN</a>
        </li>
        <li class="nav-item">
            <a class="nav-link navbar-judul" href="#">BOOKS</a>
        </li>
        <li class="nav-item">
            <a class="nav-link navbar-judul" href="{% url 'homepage:signup' %}">SIGNUP</a>
        </li>
        <li class="nav-item">
            <a class="nav-link navbar-judul" href="{% url 'homepage:signin' %}">SIGNIN</a>
        </li>
        <li class="nav-item">
            <a class="nav-link navbar-judul" href="{% url 'homepage:logout' %}">LOGOUT</a>
        </li>
        </ul>
  
    </nav>

    <div class="container">
        <input type="text" id="searchinput">
        <button id="searchbutton">
            Search
        </button>
        <table>
            <thead>
               <tr>
                   <th>
                       title
                   </th>
                   <th>
                        authors
                   </th>
                   <th>
                        publisher
                   </th>
                   <th>
                        publish date
                   </th>
               </tr> 
            </thead>
            <tbody id="tablebooks">

            </tbody>
        </table>
    </div>
    <script src="{% static 'books.js' %}"></script>
</body>

</html>

homepage/templates/Signin.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'story3CSScode.css' %}"> 
        <title>WEBSITE PROFILE ZAIDAN ARIIQ</title>
    </head>

<body>
    <!-- BAGIAN NAVIGATOR BAR -->
    <nav class="navbar navbar-expand-sm" id="navigation_bar">
        <a class="navbar-brand" href="{% url 'homepage:HTMLcode' %}" id="logo_nama">
            SELAMAT DATANG {{ user }}
        </a>
        
        
    <!-- ISI DALAM NAVIGATION BAR -->
        <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link navbar-judul" href="{% url 'homepage:hobby' %}">HOBBY</a>
        </li>
        <li class="nav-item">
            <a class="nav-link navbar-judul" href="{% url 'homepage:pendidikan' %}">PENDIDIKAN</a>
        </li>
        <li class="nav-item">
            <a class="nav-link navbar-judul" href="{% url 'homepage:contact' %}">CONTACT</a>
        </li>
        <li class="nav-item">
          <a class="nav-link navbar-judul" href="{% url 'homepage:matakuliah' %}">MATAKULIAH</a>
        </li>
        <li class="nav-item">
          <a class="nav-link navbar-judul" href="{% url 'homepage:kegiatan' %}">KEGIATAN</a>
        </li>
        <li class="nav-item">
          <a class="nav-link navbar-judul" href="{% url 'homepage:books' %}">BOOKS</a>
        </li>
        <li class="nav-item">
            <a class="nav-link navbar-judul" href="{% url 'homepage:signup' %}">SIGNUP</a>
        </li>
        <li class="nav-item">
            <a class="nav-link navbar-judul" href="#">SIGNIN</a>
        </li>
        <li class="nav-item">
            <a class="nav-link navbar-judul" href="{% url 'homepage:logout' %}">LOGOUT</a>
        </li>
        </ul>
  
    </nav>
    <h1>signin</h1>
    <form method = "post">
        {% csrf_token %}
        <input type="text" placeholder = "username" name = "username" required>
        <input type="password" placeholder = "password" name = "password" required>
        <button type = "submit">submit</button>
        
    </form>
</body>
</html>

homepage/templates/Signup.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'story3CSScode.css' %}"> 
        <title>WEBSITE PROFILE ZAIDAN ARIIQ</title>
    </head>

<body>
    <!-- BAGIAN NAVIGATOR BAR -->
    <nav class="navbar navbar-expand-sm" id="navigation_bar">
        <a class="navbar-brand" href="{% url 'homepage:HTMLcode' %}" id="logo_nama">
            SELAMAT DATANG {{ user }}
        </a>
        
        
    <!-- ISI DALAM NAVIGATION BAR -->
        <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link navbar-judul" href="{% url 'homepage:hobby' %}">HOBBY</a>
        </li>
        <li class="nav-item">
            <a class="nav-link navbar-judul" href="{% url 'homepage:pendidikan' %}">PENDIDIKAN</a>
        </li>
        <li class="nav-item">
            <a class="nav-link navbar-judul" href="{% url 'homepage:contact' %}">CONTACT</a>
        </li>
        <li class="nav-item">
          <a class="nav-link navbar-judul" href="{% url 'homepage:matakuliah' %}">MATAKULIAH</a>
        </li>
        <li class="nav-item">
          <a class="nav-link navbar-judul" href="{% url 'homepage:kegiatan' %}">KEGIATAN</a>
        </li>
        <li class="nav-item">
          <a class="nav-link navbar-judul" href="{% url 'homepage:books' %}">BOOKS</a>
        </li>
        <li class="nav-item">
            <a class="nav-link navbar-judul" href="#">SIGNUP</a>
        </li>
        <li class="nav-item">
            <a class="nav-link navbar-judul" href="{% url 'homepage:signin' %}">SIGNIN</a>
        </li>
        <li class="nav-item">
            <a class="nav-link navbar-judul" href="{% url 'homepage:logout' %}">LOGOUT</a>
        </li>
        </ul>
  
    </nav>
    <h1>singup</h1>
    <form method = "post">
        {% csrf_token %}
        <input type="text" placeholder = "username" name = "username" required>
        <input type="password" placeholder = "password" name = "password" required>
        <button type = "submit">submit</button>
        
    </form>
</body>
</html>

homepage/templates/Story6Kegiatan.html
<!DOCTYPE html>
{% load static %}

<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'story3CSScode.css' %}"> 
        <title>WEBSITE PROFILE ZAIDAN ARIIQ </title>
    </head>

    <body>
        <!-- BAGIAN NAVIGATOR BAR -->
        <nav class="navbar navbar-expand-sm" id="navigation_bar">
            <a class="navbar-brand" href="{% url 'homepage:HTMLcode' %}" id="logo_nama">
                SELAMAT DATANG {{ user }}
            </a>
            
            
        <!-- ISI DALAM NAVIGATION BAR -->
            <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link navbar-judul" href="{% url 'homepage:hobby' %}">HOBBY</a>
            </li>
            <li class="nav-item">
                <a class="nav-link navbar-judul" href="{% url 'homepage:pendidikan' %}">PENDIDIKAN</a>
            </li>
            <li class="nav-item">
                <a class="nav-link navbar-judul" href="{% url 'homepage:contact' %}">CONTACT</a>
            </li>
            <li class="nav-item">
                <a class="nav-link navbar-judul" href="{% url 'homepage:matakuliah' %}">MATAKULIAH</a>
            </li>
            <li class="nav-item">
                <a class="nav-link navbar-judul" href="{% url 'homepage:kegiatan' %}">KEGIATAN</a>
            </li>
            <li class="nav-item">
                <a class="nav-link navbar-judul" href="{% url 'homepage:books' %}">BOOKS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link navbar-judul" href="{% url 'homepage:signup' %}">SIGNUP</a>
            </li>
            <li class="nav-item">
                <a class="nav-link navbar-judul" href="{% url 'homepage:signin' %}">SIGNIN</a>
            </li>
            <li class="nav-item">
                <a class="nav-link navbar-judul" href="{% url 'homepage:logout' %}">LOGOUT</a>
            </li>
            </ul>
        </nav>
        <form method = "post">
            {% csrf_token %}
            {{form_html1}}
            <button type = "submit">submit
            </button>
        </form>
        <div class ="row">
            {% for kegiatan in list_kegiatan %}
            <div class="col-sm-4">
                <p>{{kegiatan.namaKegiatan}}</p>
                {% for pengikut in kegiatan.pengikut_set.all %}
                    <p>{{pengikut.namaPengikut}}</p>
                {% endfor %}
                <form method = "post" action="{% url 'homepage:addpengikut' kegiatan.id %}">
                    {% csrf_token %}
                    {{form_html2}}
                    <button type = "submit">submit
                    </button>
                </form>
                
            </div>
            {% endfor %}    
        </div>
    </body>
</html>  

homepage/templates/story3HTMLcode.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'story3CSScode.css' %}"> 
        <title>WEBSITE PROFILE ZAIDAN ARIIQ</title>
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        
    </head>

<body>
    <!-- BAGIAN NAVIGATOR BAR -->
    <nav class="navbar navbar-expand-sm" id="navigation_bar">
        <a class="navbar-brand" href="#" id="logo_nama">
            SELAMAT DATANG {{ user }}
        </a>
        
        
    <!-- ISI DALAM NAVIGATION BAR -->
        <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link navbar-judul" href="{% url 'homepage:hobby' %}">HOBBY</a>
        </li>
        <li class="nav-item">
            <a class="nav-link navbar-judul" href="{% url 'homepage:pendidikan' %}">PENDIDIKAN</a>
        </li>
        <li class="nav-item">
            <a class="nav-link navbar-judul" href="{% url 'homepage:contact' %}">CONTACT</a>
        </li>
        <li class="nav-item">
            <a class="nav-link navbar-judul" href="{% url 'homepage:matakuliah' %}">MATAKULIAH</a>
        </li>
        <li class="nav-item">
            <a class="nav-link navbar-judul" href="{% url 'homepage:kegiatan' %}">KEGIATAN</a>
        </li>
        <li class="nav-item">
            <a class="nav-link navbar-judul" href="{% url 'homepage:books' %}">BOOKS</a>
        </li>
        <li class="nav-item">
            <a class="nav-link navbar-judul" href="{% url 'homepage:signup' %}">SIGNUP</a>
        </li>
        <li class="nav-item">
            <a class="nav-link navbar-judul" href="{% url 'homepage:signin' %}">SIGNIN</a>
        </li>
        <li class="nav-item">
            <a class="nav-link navbar-judul" href="{% url 'homepage:logout' %}">LOGOUT</a>
        </li>
        </ul>
  
    </nav>
  
    <!-- <div class="container"> -->
        <div class="row">
            <div class="col-sm-4">
                <img src = "{% static 'ZAIDAN.jpg' %}" alt="FOTO PRIBADI ZAIDAN" id ="foto_zaidan">
              
            </div>
            <div class="col-sm-8">
                <h1>MUHAMMAD ZAIDAN ARIIQ</h1>
                <div id="kotak_deskripsi">
                    <p>
                        HALLO!<br><br>

                        NAMA SAYA ZAIDAN ARIIQ<br>
                        BIASA DIPANGGIL DENGAN SEBUTAN ZAIDAN<br><br>

                        1906400394<br><br>

                        SAYA MERUPAKAN MAHASISWA FASILKOM UI 2019 JURUSAN ILMU KOMPUTER.DI DALAM WEB SAYA INI,KAMU BISA MENEMUKAN BERBAGAI INFORMASI SINGKAT TENTANG SAYA.<br>
                    </p>
                </div>
            </div>
            
            
        </div>
        
        <div id="accordion">
            
            <div class="accitem">
                <h3>ACTIVITY</h3>
                <button onclick="return move(this,1)">V</button>
                <button onclick="return move(this,-1)">^</button>
                

            </div>            
            <div>
              <p>
                 Aktivitas ku yang sedang aku jalankan pada saat ini yaitu,
                 menjalani masa kuliah di fasilkom UI angkatang 2019,dan juga
                 menjalani beberapa kegiatan yang ada di fakultas tersebut.
              </p>
              
            </div>
            <div class="accitem">
                <h3>ORGANITATION</h3> 
                <button onclick="return move(this,1)">V</button>
                <button onclick="return move(this,-1)">^</button>
                

            </div>        
            <div>
              <p>
                Organisasi yang pernah aku jalani yaitu mengikuti SBF fasilkom 2019 pada tahun lalu
              </p>
              
            </div>
            <div class="accitem">
                <h3>ACHIEVEMENT</h3> 
                <button onclick="return move(this,1)">V</button>
                <button onclick="return move(this,-1)">^</button>
                

            </div>        
            <div>
              <ul>
                <li>LOMBA MATEMATIKA SD</li>
                <li>LOMBA AGAMA ISLAM SD</li>
                <li>LOMBA FISIKA SMP</li>
              </ul>
              
            </div>
            <div class="accitem">
                <h3>MY EXPERIENCE STUDY IN CSUI 2019</h3> 
                <button onclick="return move(this,1)">V</button>
                <button onclick="return move(this,-1)">^</button>
                

            </div>        
            <div>
              <p>
                Penagalaman yang "experience" yang sedang aku lalui untuk sekarang
                ini yaitu menyelesaikan matkul penting dahulu.
              </p>
              

            </div>
        </div>
           



           




    <!-- untuk meng import file accordion.js ke filehtml utamanya  -->
<script src="{% static 'accordion1.js' %}"></script>
</body>

</html>

homepage/templates/story5MatKul.html
<!DOCTYPE html>
{% load static %}

<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'story3CSScode.css' %}"> 
        <title>WEBSITE PROFILE ZAIDAN ARIIQ </title>
    </head>

    <body>
        <!-- BAGIAN NAVIGATOR BAR -->
        <nav class="navbar navbar-expand-sm" id="navigation_bar">
            <a class="navbar-brand" href="{% url 'homepage:HTMLcode' %}" id="logo_nama">
                SELAMAT DATANG {{ user }}
            </a>
            
            
        <!-- ISI DALAM NAVIGATION BAR -->
            <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link navbar-judul" href="#">HOBBY</a>
            </li>
            <li class="nav-item">
                <a class="nav-link navbar-judul" href="{% url 'homepage:pendidikan' %}">PENDIDIKAN</a>
            </li>
            <li class="nav-item">
                <a class="nav-link navbar-judul" href="{% url 'homepage:contact' %}">CONTACT</a>
            </li>
            <li class="nav-item">
                <a class="nav-link navbar-judul" href="{% url 'homepage:matakuliah' %}">MATAKULIAH</a>
            </li>
            <li class="nav-item">
                <a class="nav-link navbar-judul" href="{% url 'homepage:kegiatan' %}">KEGIATAN</a>
            </li>
            <li class="nav-item">
                <a class="nav-link navbar-judul" href="{% url 'homepage:books' %}">BOOKS</a>
            </li>
            <li class="nav-item">
                <a class="nav-link navbar-judul" href="{% url 'homepage:signup' %}">SIGNUP</a>
            </li>
            <li class="nav-item">
                <a class="nav-link navbar-judul" href="{% url 'homepage:signin' %}">SIGNIN</a>
            </li>
            <li class="nav-item">
                <a class="nav-link navbar-judul" href="{% url 'homepage:logout' %}">LOGOUT</a>
            </li>
            </ul>
        </nav>
        <form method = "post">
        {% csrf_token %}
        {{form_html}}
        <button type = "submit">submit
        </button>
        </form>
        {% for matkul in list_matkul %}
        <p>{{matkul.namaMatkul}}</p>
        <P>{{matkul.namaDosen}}</p>
        <p>{{matkul.jumlahSks}}</p>
        <p>{{matkul.descMatkul}}</p>
        <p>{{matkul.semester}}</p>
        <p>{{matkul.ruangKelas}}</p>
        <a href = "{% url 'homepage:delete' matkul.id  %}">delete</a>
        {% endfor %}
    </body> 
</html>   